server:
  port: 0 
eureka:
  instance:
    instanceId: ${spring.application.instance_id:${random.value}}  
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://127.0.0.1:8888/eureka/, http://127.0.0.1:8889/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:
  application:
    name: produto2